### ISSUE TITLE
Swiping multiple times and text animation

### ISSUE THREAD

**Issue by SimonMarquis** [foxykeep/LifeCounter#3]
When you swipe at least 2 times in the same direction (to increment the score) the text animation is reset.
It would be great if the text could just duplicates itself, in order to run multiples animations at the same time?

**Comment by foxykeep** [comment]
I'll maybe add that in the future. but that's not a big requirement for now.

For the gory details, I'm just using a TextView that I animate using AnimationUtils. Having the text duplicate requires to write a custom View just for that so that I can draw multiple text at the same time. Also that means I'll be losing the hardware acceleration which is given for free with the AnimationUtils framework.

**Comment by SimonMarquis** [comment]
Or maybe you could just add a TextView to a container whenever you trigger the action.
Then you animate the newly created TextView, and finally, at the end of the animation, you just remove it from it's container.
What do you think about this way?

**Comment by foxykeep** [comment]
I spoke with the designer of the app and this is working as she has intended it. So keeping it like that.
